In [2]:
import numpy as np
import pandas as pd

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [4]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [5]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [6]:
np.cov(zp, ks) #несмещенная

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [8]:
np.cov(zp, ks, ddof=0) #смещенная

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [10]:
std_zp = np.std(zp, ddof =1)
std_ks = np.std(ks, ddof =1)
cov_zpks = np.cov(zp, ks, ddof =1)[0][1]
pirson_zpks = cov_zpks/(std_zp*std_ks)
pirson_zpks

0.887490092073916

In [11]:
pirson_np_zpks = np.corrcoef(zp, ks)
pirson_np_zpks

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [12]:
df_zpks = pd.DataFrame({'zp':[35, 45, 190, 200, 40, 70, 54, 150, 120, 110], 'ks':[401, 574, 874, 919, 459, 739, 653, 902, 746, 832]})

In [13]:
df_zpks.head()

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459

In [15]:
df_zpks['zp'].corr(df_zpks['ks'])

0.8874900920739162